# Theme: kanagawa-dragon — https://github.com/rebelot/kanagawa.nvim

# Main bg
theme[main_bg]="#181616"

# Main text color
theme[main_fg]="#c5c9c5"

# Title color for boxes
theme[title]="#C8C093"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c4746e"

# Background color of selected item in processes box
theme[selected_bg]="#43242B"

# Foreground color of selected item in processes box
theme[selected_fg]="#C8C093"

# Color of inactive/disabled text
theme[inactive_fg]="#625e5a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b6927b"

# Cpu box outline color
theme[cpu_box]="#393836"

# Memory/disks box outline color
theme[mem_box]="#393836"

# Net up/down box outline color
theme[net_box]="#393836"

# Processes box outline color
theme[proc_box]="#393836"

# Box divider line and small boxes line color
theme[div_line]="#393836"

# Temperature graph colors
theme[temp_start]="#87a987"
theme[temp_mid]="#c4b28a"
theme[temp_end]="#c4746e"

# CPU graph colors
theme[cpu_start]="#87a987"
theme[cpu_mid]="#c4b28a"
theme[cpu_end]="#c4746e"

# Mem/Disk free meter
theme[free_start]="#87a987"
theme[free_mid]="#c4b28a"
theme[free_end]="#c4746e"

# Mem/Disk cached meter
theme[cached_start]="#87a987"
theme[cached_mid]="#c4b28a"
theme[cached_end]="#c4746e"

# Mem/Disk available meter
theme[available_start]="#87a987"
theme[available_mid]="#c4b28a"
theme[available_end]="#c4746e"

# Mem/Disk used meter
theme[used_start]="#87a987"
theme[used_mid]="#c4b28a"
theme[used_end]="#c4746e"

# Download graph colors
theme[download_start]="#87a987"
theme[download_mid]="#c4b28a"
theme[download_end]="#c4746e"

# Upload graph colors
theme[upload_start]="#87a987"
theme[upload_mid]="#c4b28a"
theme[upload_end]="#c4746e"

