-- CachyOS Hyprland Configuration

require("modules.animations")
require("modules.autostart")
require("modules.colors")
require("modules.decorations")
require("modules.variables")
require("modules.environment")
require("modules.inputs")
require("modules.binds")
require("modules.apps")
require("modules.wsgroups")
require("modules.controlcenter")
require("modules.misc")
require("modules.monitors")
require("modules.windowrules")
require("modules.workspacerules")
