-- CachyOS Hyprland Configuration

-- the colour theme (local/bin/theme): its files are made before the modules read them (a new PC, a synced change)
pcall(os.execute, "~/.local/bin/theme restore >/dev/null 2>&1")

require("modules.animations")
require("modules.autostart")
require("modules.colors")
require("modules.decorations")
require("modules.variables")
require("modules.environment")
require("modules.inputs")
require("modules.binds")
require("modules.apps")
require("modules.codepair")   -- before wsgroups: it sets PAIR_WS
require("modules.wsgroups")
require("modules.wallblur")   -- the wallpaper blurs behind windows (scripts/wallpaper.sh)
require("modules.misc")
require("modules.monitors")
require("modules.windowrules")
require("modules.workspacerules")
-- last, so their values win: generated by the Settings panel (Super + I) from settings.json, and
-- settings.local.json for this PC only (gitignored, so it may not exist yet)
require("modules.settings")
pcall(require, "modules.settings_local")
